name: Build and Deploy Spring Boot to Azure

on:
  push:
    branches:
      - main

env:
  ACR_LOGIN_SERVER: orderdemoregistry2026.azurecr.io
  IMAGE_NAME: order-service
  RESOURCE_GROUP: rg-order-demo
  APP_NAME: order-demo-container-2026

jobs:

  build:
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ steps.image.outputs.tag }}

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '21'
          cache: maven

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Read DB Password from Key Vault
        run: |
          DB_PASSWORD=$(az keyvault secret show \
            --vault-name order-demo-kv-2026 \
            --name db-password \
            --query value \
            --output tsv)

          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} \
            .

      - name: Login to Azure Container Registry
        run: |
          az acr login --name orderdemoregistry2026

      - name: Push Docker image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

      - name: Set image tag
        id: image
        run: |
          echo "tag=${{ github.sha }}" >> "$GITHUB_OUTPUT"


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Docker image to Azure App Service
        run: |
          az webapp config container set \
            --resource-group $RESOURCE_GROUP \
            --name $APP_NAME \
            --docker-custom-image-name $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ needs.build.outputs.image-tag }} \
            --docker-registry-server-url https://$ACR_LOGIN_SERVER